language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_script:
  - "npm install"
  - "npm install -g sequelize-cli"
  - "psql -c 'create database pmsTest;' -U postgres"
script:
  - "npm test"
services:
  - postgresql
